### ISSUE TITLE
TypeError: 'module' object is not callable referring to "field_type(value)"

### ISSUE THREAD

**Issue by binari2** [dfurtado/dataclass-csv#29]
I am hoping this is just a naive user question:

refer to this line of code in the DataClassReader:

https://github.com/dfurtado/dataclass-csv/blob/c33804ed12f51e224872ddb2cffc5eeefeda2201/dataclass_csv/dataclass_reader.py#L197

Task: 

Using subclasses defining a logical data model, read a csv file with name different than in the data model.  In the DataClassReader using the .map method to map columns names in the csv file to field names in the sales class.  The class 'sales' includes 'markets' and 'products' master data as subclasses.

code and traceback:
-------------------------------------

from dataclasses import dataclass, field
import dataclass_csv 
import datetime

#define dataclasses to align with a logical dimensional data model
@dataclass
class markets:
    market_id : str = field(metadata={'accept_whitespaces': True},init=False)
    market : str = field(metadata={'accept_whitespaces': True},init=True)

@dataclass
class products:
    upc : str = field(metadata={'accept_whitespaces': True},init=True)
    product : str = field(metadata={'accept_whitespaces': True},init=True)
    
@dataclass
@dataclass_csv.dateformat('%Y-%m-%d')
class sales(markets, products):
    weekend : datetime = field(metadata={'accept_whitespaces': False},init=True)
    total_units : float = field(metadata={'accept_whitespaces': False},init=True,default=0.00000)
    total_revenue : float = field(metadata={'accept_whitespaces': False},init=True,default=0.00000)

#assume all data is provided in a single file.  

with open('sales.csv','r') as infile:
    reader = dataclass_csv.DataclassReader(infile, sales)
    reader.map('Week').to('weekend')
    reader.map('Market').to('market')
    reader.map('EANUPC').to('upc')
    reader.map('Product Description').to('product')
    reader.map('Sales Units').to('total_units')
    reader.map('Sales Dollars').to('total_revenue')
    for row in reader:
        print(row)

At this point I am expecting the see records like:
sales(weekend = ..., ..., total_revenue = 100.00)
...

However I get the following traceback on the first iteration of the for loop:
-------------------------------------

Traceback (most recent call last):

  File "<ipython-input-38-241aa819dfb3>", line 44, in <module>
    for row in reader:

  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/dataclass_csv/dataclass_reader.py", line 211, in __next__
    return self._process_row(row)

  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/dataclass_csv/dataclass_reader.py", line 195, in _process_row
    transformed_value = field_type(value)

TypeError: 'module' object is not callable

------------------

Looking at the dataclass_reader.py I see "field_type = field.type", but not defined as a callable function anywhere.  

Python 3.7.0 64 bit
Spyder IDE 3.3.6
Mac OS

**Comment by binari2** [comment]
User Error.

field_type(value) was not working given how I had set up the datetime typing in the sales class.  I modified the sales class to the following:

@dataclass
@dateformat('%Y-%m-%d')
class sales(markets, products):
    weekend : datetime.datetime
    total_units : float 
    total_revenue : float 

and obtain the expected output:

sales(upc='1234567', product='Shaving Cream', market_id='C001', market='Brandega', weekend=datetime.datetime(2020, 1, 7, 0, 0), total_units=100.0, total_revenue=495.0)
sales(upc='1234567', product='Shaving Cream', market_id='C001', market='Brandega', weekend=datetime.datetime(2020, 1, 14, 0, 0), total_units=150.0, total_revenue=760.0)
sales(upc='1234895', product='Toothpaste', market_id='C002', market='CPCo', weekend=datetime.datetime(2020, 1, 7, 0, 0), total_units=200.0, total_revenue=600.0)
sales(upc='1234895', product='Toothpaste', market_id='C002', market='CPCo', weekend=datetime.datetime(2020, 1, 14, 0, 0), total_units=150.0, total_revenue=500.0)
